/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xwang_cordova_irc_IRCClient */

#ifndef _Included_xwang_cordova_irc_IRCClient
#define _Included_xwang_cordova_irc_IRCClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xwang_cordova_irc_IRCClient
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xwang_cordova_irc_IRCClient_initialize
  (JNIEnv *, jobject);

/*
 * Class:     xwang_cordova_irc_IRCClient
 * Method:    connect
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_xwang_cordova_irc_IRCClient_connect
  (JNIEnv *, jobject, jstring, jint, jstring, jstring, jstring, jstring);

/*
 * Class:     xwang_cordova_irc_IRCClient
 * Method:    disconnect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xwang_cordova_irc_IRCClient_disconnect
  (JNIEnv *, jobject);

/*
 * Class:     xwang_cordova_irc_IRCClient
 * Method:    isConnected
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_xwang_cordova_irc_IRCClient_isConnected
  (JNIEnv *, jobject);

/*
 * Class:     xwang_cordova_irc_IRCClient
 * Method:    join
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_xwang_cordova_irc_IRCClient_join
  (JNIEnv *, jobject, jstring);

/*
 * Class:     xwang_cordova_irc_IRCClient
 * Method:    message
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_xwang_cordova_irc_IRCClient_message
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
